# fly.toml app configuration file generated for app-uoh-lw-green-shadow-1884 on 2025-02-07T18:22:14+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#


[build]

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
