[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
candid = "0.10"
errors = { path = "../errors" }
ic-cdk = "0.12"
ic-stable-structures = "0.6.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.138"
thiserror = "1.0.63"
