name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm i
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Install dfx
        uses: dfinity/setup-dfx@main
      - name: Start replica
        run: dfx start --background
      - name: Generate candid declarations
        run: dfx deploy
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: ./src/app_frontend
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: "main"